theme = "drew"

[editor]
auto-reload = true
true-color = true
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true

[keys.normal]
- = [
  ":sh rm -f /tmp/unique-file",
  ":insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file",
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ":open %sh{cat /tmp/unique-file}",
  ":redraw",
]
space = { g = { r = [":reset-diff-change"] }, r = ":reload-all", l = { r = "rename_symbol", a = "code_action" }, a = { p = ":sh tmux new-window 'nvim +%{cursor_line} %{buffer_name}'" } }
esc = ["collapse_selection", "keep_primary_selection"]
# Search for word under cursor
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_next",
]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
C-space = ["completion"]

[keys.select]
p = "replace_selections_with_clipboard"  # No life without this
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
