[ui.colors]
"selected" = { bg = "#444444" }

# [ui.tracer]
# enabled = true

[preview]
show_at_start = false

[revisions]
log_batching = true
# template = 'builtin_log_oneline' # overrides jj's templates.log
# template = 'builtin_log_comfortable' # overrides jj's templates.log
# revset = "here"

[custom_commands]
"pick commit" = { args = ["commit", "-i", "--tool", "gitpatch"], show = "interactive" }
"rebase all prs" = { args = ["rebase", "-r", "mutable() & mine()", "-d", "main"] }
"new main" = { args = ["new", "main"] }
"new after selected" = { key = ["N"], args = [
  "new",
  "-A",
  "$change_id",
  "--no-edit",
] }
"edit file" = { key = ["e"], args = [ "util", "exec", "open-in-zed", "$file" ] }
