#:tombi toml-version = "v1.1.0-preview"

theme = "drew"


[editor]
true-color = true
line-number = "relative"
bufferline = "always"
end-of-line-diagnostics = "hint"
color-modes = true

[editor.soft-wrap]
enable = true


[editor.inline-diagnostics]
cursor-line = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"-" = [
  ":sh rm -f /tmp/unique-file",
  ":insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file",
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ":open %sh{cat /tmp/unique-file}",
  ":redraw",
  ':set mouse false',
  ':set mouse true',
]
[keys.normal.g]
x = ":buffer-close"

[keys.normal.space]
e = "file_explorer_in_current_buffer_directory"
p = "goto_last_accessed_file"
r = ":reload-all"
x = ":buffer-close"

[keys.normal.space.s]
s = "symbol_picker"
f = [
  ":sh rm -f /tmp/unique-file",
  ":insert-output sh -c 'zask find_files > /tmp/unique-file 2>&1' > /dev/null",
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ":open %sh{cat /tmp/unique-file}",
  ":redraw",
]

[keys.normal.space.g]
r = ":reset-diff-change"
c = "changed_file_picker"

[keys.normal.space.l]
r = "rename_symbol"
a = "code_action"

[keys.normal.space.a]
p = ":sh tmux new-window 'nvim +%{cursor_line} %{buffer_name}'"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
C-space = "completion"
C-l = "move_char_right"
C-h = "move_char_left"

[keys.select]
p = "replace_selections_with_clipboard"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
