#!/usr/bin/env bash

# Bootstrap homebrew if not installed
if ! command -v brew &>/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>"$HOME/.zprofile"
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  echo "brew already installed"
fi

# Helper function to check if an array contains a value
function contains() {
  local needle="$1"
  local haystack=("${@:2}") # Get the array from the arguments
  for element in "${haystack[@]}"; do
    if [[ "$element" == "$needle" ]]; then
      return 0 # Found
    fi
  done
  return 1 # Not found
}

# Prefetch installed casks
INSTALLED_CASKS=($(brew list --cask))

function install_cask_if_not_installed() {
  local app_name="$1"
  local cask_name="$2"

  # Check if the cask is already in the prefetched list
  if contains "$cask_name" "${INSTALLED_CASKS[@]}"; then
    echo "$cask_name already installed"
  else
    echo "installing $cask_name"
    brew install --cask "$cask_name"
  fi
}

install_cask_if_not_installed "karabiner-elements" "karabiner-elements"
install_cask_if_not_installed "spotify" "spotify"
install_cask_if_not_installed "ghostty" "ghostty"
install_cask_if_not_installed "raycast" "raycast"
install_cask_if_not_installed "aerospace" "nikitabobko/tap/aerospace"
install_cask_if_not_installed "zen" "zen"
install_cask_if_not_installed "legcord" "legcord"
install_cask_if_not_installed "cursor" "cursor"
