#!/usr/bin/env bash

# Bootstrap homebrew if not installed
if ! command -v brew &>/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>"$HOME/.zprofile"
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  echo "brew already installed"
fi

# Get the list of installed casks once
INSTALLED_CASKS=$(brew list --cask)

function install_cask_if_not_installed() {
  local cask_name="$1"
  if echo "$INSTALLED_CASKS" | grep -q "^$cask_name$"; then
    echo "$cask_name already installed"
  else
    echo "installing $cask_name"
    brew install --cask "$cask_name"
  fi
}

install_cask_if_not_installed "karabiner-elements"
install_cask_if_not_installed "spotify"
install_cask_if_not_installed "ghostty"
install_cask_if_not_installed "raycast"
install_cask_if_not_installed "aerospace"
install_cask_if_not_installed "zen"
install_cask_if_not_installed "legcord"
install_cask_if_not_installed "cursor"
