#!/usr/bin/env bash

mkdir -p $HOME/.config/ghostty
cp $HOME/dev-env/config/ghostty/config $HOME/.config/ghostty/config

# only if dev plat is mac
if [ "$DEV_PLAT" == "mac" ]; then
  mkdir -p $HOME/.config/aerospace/
  cp $HOME/dev-env/config/aerospace/aerospace.toml $HOME/.config/aerospace/aerospace.toml
fi

if [ "$DEV_PLAT" == "arch" ]; then
  mkdir -p $HOME/.config/hypr/
  cp $HOME/dev-env/config/hyprland/hyprland.conf $HOME/.config/hypr/hyprland.conf
  cp $HOME/dev-env/config/hyprland/hyprpaper.conf $HOME/.config/hypr/hyprpaper.conf

  mkdir -p $HOME/.config/waybar/
  cp -a $HOME/dev-env/config/waybar/. $HOME/.config/waybar
fi

# rm -rf $HOME/.config/nvim
# mkdir -p $HOME/.config/nvim/
# cp -a $HOME/dev-env/config/nvim/. $HOME/.config/nvim/

# Tmux
rm -rf $HOME/.tmux.conf
cp $HOME/dev-env/config/tmux/.tmux.conf $HOME/.tmux.conf

rm -rf $HOME/.config/atuin
mkdir -p $HOME/.config/atuin/
cp -a $HOME/dev-env/config/atuin/. $HOME/.config/atuin/

mkdir -p $HOME/.config/fish/
cp -a $HOME/dev-env/config/fish/. $HOME/.config/fish/

# mkdir -p $HOME/.config/opencode/
# cp -a $HOME/dev-env/config/opencode/. $HOME/.config/opencode/

ln -sfn $HOME/dev-env/config/mprocs $HOME/.config/mprocs
ln -sfn $HOME/dev-env/config/yazi $HOME/.config/yazi
ln -sfn $HOME/dev-env/config/jjui $HOME/.config/jjui
ln -sfn $HOME/dev-env/config/new-nvim/ $HOME/.config/nvim
ln -sfn $HOME/dev-env/config/nvim/ $HOME/.config/old-nvim
ln -sfn $HOME/dev-env/config/opencode/ $HOME/.config/opencode
ln -sfn $HOME/dev-env/config/helix/ $HOME/.config/helix
