#!/usr/bin/env bash

mkdir -p $HOME/.config/ghostty
cp $HOME/dev-env/config/ghostty/config $HOME/.config/ghostty/config

# only if dev plat is mac
if [ "$DEV_PLAT" == "mac" ]; then
  mkdir -p $HOME/.config/aerospace/
  cp $HOME/dev-env/config/aerospace/aerospace.toml $HOME/.config/aerospace/aerospace.toml
fi

if [ "$DEV_PLAT" == "arch" ]; then
  mkdir -p $HOME/.config/hypr/
  cp $HOME/dev-env/config/hyprland/hyprland.conf $HOME/.config/hypr/hyprland.conf
  cp $HOME/dev-env/config/hyprland/hyprpaper.conf $HOME/.config/hypr/hyprpaper.conf

  mkdir -p $HOME/.config/waybar/
  cp -a $HOME/dev-env/config/waybar/. $HOME/.config/waybar
fi

rm -rf $HOME/.config/nvim
mkdir -p $HOME/.config/nvim/
cp -a $HOME/dev-env/config/nvim/. $HOME/.config/nvim/

# Tmux
cp $HOME/dev-env/config/tmux/.tmux.conf $HOME/.tmux.conf

rm -rf $HOME/.config/atuin
mkdir -p $HOME/.config/atuin/
cp -a $HOME/dev-env/config/atuin/. $HOME/.config/atuin/

mkdir -p $HOME/.config/helix/
cp -a $HOME/dev-env/config/helix/. $HOME/.config/helix/

ln -sfn $HOME/dev-env/config/mprocs $HOME/.config/mprocs
