#!/usr/bin/env bash

echo "install script - mac"

# Prefetch installed casks outside the function
readarray -t INSTALLED_CASKS < <(brew list --cask)

function install_if_not_installed() {
  if ! command -v "$1" &>/dev/null; then
    echo "installing $2"
    brew install "$2"
  else
    echo "$1 already installed"
  fi
}

# Helper function to check if an array contains a value
function contains() {
  local needle="$1"
  local haystack=("${@:2}") # Get the array from the arguments
  for element in "${haystack[@]}"; do
    if [[ "$element" == "$needle" ]]; then
      return 0 # Found
    fi
  done
  return 1 # Not found
}

# Bootstrap homebrew if not installed
if ! command -v brew &>/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>"$HOME/.zprofile"
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  echo "brew already installed"
fi

install_if_not_installed "hx" "helix"
install_if_not_installed "lazygit" "jesseduffield/lazygit/lazygit"
install_if_not_installed "tmux" "tmux"
install_if_not_installed "nvim" "neovim"
install_if_not_installed "jj" "jj"

if ! command -v node &>/dev/null; then
  sudo curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n | sudo bash -s install lts
fi

if ! command -v yarn &>/dev/null; then
  sudo npm install --global yarn
fi
