#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

echo "install script"

if [[ "$DEV_PLAT" == "mac" ]]; then
  source "$script_dir/install-scripts/install-mac"
fi

if [[ "$DEV_PLAT" == "arch" ]]; then
  source "$script_dir/install-scripts/install-arch"
fi
