#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

echo "install script"

if [[ "$DEV_PLAT" == "mac" ]]; then
  source "$script_dir/install-scripts/install-mac"
fi

if [[ "$DEV_PLAT" == "arch" ]]; then
  source "$script_dir/install-scripts/install-arch"
fi

if ! command -v cargo &> /dev/null; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

if ! command -v bun &> /dev/null; then
  curl -fsSL https://bun.sh/install | bash
fi
