#!/usr/bin/env bash

echo "install script - mac"

function install_if_not_installed() {
  if ! command -v "$1" &>/dev/null; then
    echo "installing $2"
    brew install "$2"
  else
    echo "$1 already installed"
  fi
}

function install_cask_if_not_installed() {
  local app_name="$1"  # The user-friendly name or command to check for (less reliable for casks)
  local cask_name="$2" # The actual Homebrew cask name

  # Check if the cask is already installed
  if brew list --cask "$cask_name" &>/dev/null; then
    echo "$cask_name already installed"
  else
    echo "installing $cask_name"
    brew install --cask "$cask_name"
  fi
}

# Boostrap homebrew if not installed
if ! command -v brew &>/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo >>/Users/drew/.zprofile
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>/Users/drew/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  echo "brew already installed"
fi

install_if_not_installed "hx" "helix"
install_if_not_installed "lazygit" "jesseduffield/lazygit/lazygit"
install_if_not_installed "tmux" "tmux"
install_if_not_installed "nvim" "neovim"

install_cask_if_not_installed "karabiner-elements" "karabiner-elements"
install_cask_if_not_installed "spotify" "spotify"

if ! command -v node &>/dev/null; then
  sudo curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n | sudo bash -s install lts
fi

if ! command -v yarn &>/dev/null; then
  sudo npm install --global yarn
fi
