#!/usr/bin/env bash

echo "install script - mac"

# Bootstrap homebrew if not installed
if ! command -v brew &>/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>"$HOME/.zprofile"
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  echo "brew already installed"
fi

# Get the list of installed formulae once
INSTALLED_FORMULAE=$(brew list --formula)

# Get the list of tapped repositories once
TAPPED_REPOS=$(brew tap)

function tap_if_not_tapped() {
  local repo="$1"
  if echo "$TAPPED_REPOS" | grep -q "^$repo$"; then
    echo "$repo already tapped"
  else
    echo "tapping $repo"
    brew tap "$repo"
  fi
}

function install_if_not_installed() {
  local pkg="$1"
  if echo "$INSTALLED_FORMULAE" | grep -q "^$pkg$"; then
    echo "$pkg already installed"
  else
    echo "installing $pkg"
    brew install "$pkg"
  fi
}

# Tap necessary repositories
tap_if_not_tapped "dbcli/tap"

# Install formulae
install_if_not_installed "helix"
install_if_not_installed "lazygit"
install_if_not_installed "tmux"
install_if_not_installed "neovim"
install_if_not_installed "fzf"
install_if_not_installed "carapace"
install_if_not_installed "zoxide"
install_if_not_installed "eza"
install_if_not_installed "sesh"
install_if_not_installed "yazi"
install_if_not_installed "jq"
install_if_not_installed "go"
install_if_not_installed "ripgrep"
install_if_not_installed "openapi-tui"
install_if_not_installed "nushell"
install_if_not_installed "mprocs"
install_if_not_installed "prettierd"
install_if_not_installed "gh"
install_if_not_installed "lua-language-server"
install_if_not_installed "clojure/tools/clojure"
install_if_not_installed "sst/tap/opencode"
install_if_not_installed "pueue"
install_if_not_installed "litecli"

if ! command -v node &>/dev/null; then
  sudo curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n | sudo bash -s install lts
fi

if ! command -v yarn &>/dev/null; then
  sudo npm install --global yarn
fi
