#!/usr/bin/env bash

echo "install script - mac"

# Bootstrap homebrew if not installed
if ! command -v brew &>/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>"$HOME/.zprofile"
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  echo "brew already installed"
fi

# Get the list of installed formulae once
INSTALLED_FORMULAE=$(brew list --formula)

function install_if_not_installed() {
  local pkg="$1"
  if echo "$INSTALLED_FORMULAE" | grep -q "^$pkg$"; then
    echo "$pkg already installed"
  else
    echo "installing $pkg"
    brew install "$pkg"
  fi
}

install_if_not_installed "helix"
install_if_not_installed "lazygit"
install_if_not_installed "tmux"
install_if_not_installed "neovim"
install_if_not_installed "fzf"
install_if_not_installed "carapace"
install_if_not_installed "zoxide"
install_if_not_installed "eza"
install_if_not_installed "sesh"
install_if_not_installed "yazi"
install_if_not_installed "jq"
install_if_not_installed "go"
install_if_not_installed "ripgrep"
install_if_not_installed "openapi-tui"

if ! command -v node &>/dev/null; then
  sudo curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n | sudo bash -s install lts
fi

if ! command -v yarn &>/dev/null; then
  sudo npm install --global yarn
fi
