#!/usr/bin/env bash

echo "install script - mac"

# Bootstrap homebrew if not installed
if ! command -v brew &>/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>"$HOME/.zprofile"
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  echo "brew already installed"
fi

# Get the list of installed formulae once
readarray -t INSTALLED_FORMULAE < <(brew list --formula)

function install_if_not_installed() {
  local pkg="$1"
  for installed in "${INSTALLED_FORMULAE[@]}"; do
    if [[ "$installed" == "$pkg" ]]; then
      echo "$pkg already installed"
      return
    fi
  done
  echo "installing $pkg"
  brew install "$pkg"
}

# Helper function to check if an array contains a value
function contains() {
  local needle="$1"
  local haystack=("${@:2}") # Get the array from the arguments
  for element in "${haystack[@]}"; do
    if [[ "$element" == "$needle" ]]; then
      return 0 # Found
    fi
  done
  return 1 # Not found
}

install_if_not_installed "helix"
install_if_not_installed "lazygit"
install_if_not_installed "tmux"
install_if_not_installed "neovim"
install_if_not_installed "fzf"
install_if_not_installed "carapace"
install_if_not_installed "zoxide"
install_if_not_installed "eza"
install_if_not_installed "sesh"
install_if_not_installed "yazi"
install_if_not_installed "jq"
install_if_not_installed "go"
install_if_not_installed "ripgrep"

if ! command -v node &>/dev/null; then
  sudo curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n | sudo bash -s install lts
fi

if ! command -v yarn &>/dev/null; then
  sudo npm install --global yarn
fi
