#!/usr/bin/env bash
echo "install script - arch"

function install_if_not_installed() {
  if ! pacman -Q "$1" &>/dev/null; then
    echo "installing $1"
    sudo pacman -S --noconfirm "$1"
  else
    echo "$1 already installed"
  fi
}

install_if_not_installed "ghostty"
install_if_not_installed "helix"
install_if_not_installed "tmux"
install_if_not_installed "neovim"
install_if_not_installed "jujutsu"
install_if_not_installed "lazygit"
install_if_not_installed "fzf"
install_if_not_installed "zsh"
install_if_not_installed "eza"
install_if_not_installed "jq"
install_if_not_installed "hyprpaper"
install_if_not_installed "waybar"
install_if_not_installed "yazi"
install_if_not_installed "inotify-tools"
install_if_not_installed "spotify-launcher"

