#!/usr/bin/env bash
echo "install script - arch"

function install_if_not_installed() {
  if ! command -v "$1" &>/dev/null; then
    echo "installing $2"
    sudo pacman -S --noconfirm "$2"
  else
    echo "$1 already installed"
  fi
}

install_if_not_installed "ghostty" "ghostty"
install_if_not_installed "helix" "helix"
install_if_not_installed "tmux" "tmux"
install_if_not_installed "nvim" "neovim"
install_if_not_installed "jj" "jujutsu"
install_if_not_installed "lazygit" "lazygit"
install_if_not_installed "fzf" "fzf"
install_if_not_installed "sesh" "sesh-bin"
