require("config.options")
require("config.keymap")
require("core.lazy")
require("core.lsp")
require("custom.splitargs")
require("custom.editors")
require("custom.kwik-files").setup()
require("custom.nushell").setup()

vim.cmd("highlight! HarpoonInactive guibg=NONE guifg=#63698c")
vim.cmd("highlight! link HarpoonActive IncSearch")
vim.cmd("highlight! link HarpoonNumberActive IncSearch")
vim.cmd("highlight! HarpoonNumberInactive guibg=NONE guifg=#7aa2f7")
vim.cmd("highlight! WinBar guibg=NONE guifg=#7aa2f7")
vim.cmd("highlight! WinBarNC guibg=NONE guifg=#7aa2f7")

-- vim.cmd.colorscheme("catppuccin-macchiato")
vim.cmd.colorscheme("sonokai")
