[tools]
bun = "latest"
helix = "latest"
jj = "latest"
just = "latest"
lazydocker = "latest"
node = "latest"
yazi = "latest"
pnpm = "latest"
github-cli = "latest"
bitwarden = "latest"
fnox = "latest"
jq = "latest"
usage = "latest"
"github:mgood/tuisage" = "latest"
pitchfork = "latest"
watchexec = "latest"
"cargo:tomli" = "latest"

[tasks]
tui = { description = "TUI to run mise tasks", run = 'tuisage --cmd "mise run" mise tasks ls --usage' }

[shell_alias]
icli = "node /Users/drew/programs/instant/client/packages/cli/dist/index.js"
medit = "mise edit ~/dev-env/dots/.config/mise/config.toml"
super = "mise super"
