[user]
name = "Drew Harris"
email = "drew@drewh.net"

[merge-tools.nvim]
program = "/opt/homebrew/bin/nvim"
edit-args = ["-c", "DiffEditor $left $right $output"]

[ui]
default-command = ["log", "-T", "builtin_log_comfortable"]
pager = ["delta", "--pager", "less -FRX"]
conflict-marker-style = "git"
diff-formatter = ["delta", "$left", "$right", "--file-transformation", "s|.*/jj-diff-[^/]*/[^/]*/||"]
# default-command = "log"

[template-aliases]
'format_short_signature(signature)' = 'signature.name()'
'format_timestamp(timestamp)' = 'timestamp.ago()'

[aliases]
d = ["desc", "-m"]
n = ["new"]
reheat = ["rebase", "-d", "trunk()", "-s", "all:roots(trunk()..stack(@))"]
l = ["log", "-r", "work"]

[merge-tools.gitpatch]
program = "sh"
edit-args = ["-c", '''
  set -eu
  rm -f "$right/JJ-INSTRUCTIONS"
  git -C "$left" init -q
  git -C "$left" add -A
  git -C "$left" commit -q -m baseline --allow-empty
  mv "$left/.git" "$right"
  git -C "$right" add --intent-to-add --ignore-removal .
  git -C "$right" add -p
  git -C "$right" diff-index --quiet --cached HEAD && { echo "No changes done, aborting split."; exit 1; }
  git -C "$right" commit -q -m split
  git -C "$right" reset -q --hard
''',
]


lazyjj.skip-confirmations = true


[revset-aliases]
'trunks' = 'main' # big list of branch names
'local(x)' = 'reachable(x, ~::trunks)'
simple = 'ancestors(local(@), 2)'
here = 'ancestors(reachable(@, trunk()..), 2) | trunk()'
"active(rev)" = "(ancestors(rev) | descendants(rev)) ~ immutable()"
work = "active(@) | active(prev)"

