#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Usage: $0 <app_id>" >&2
	    exit 1
		fi

		app_id="$1"

		niri msg --json windows | jq -r --arg app_id "$app_id" \
		    '.[] | select(.app_id == $app_id) | .id' | head -n 1
