#!/bin/bash
$HOME/programs/home/activate-computer.nu

# PC monitor
niri msg output DP-1 on
niri msg output DP-1 mode 3840x2160@59.997

# TV
niri msg output HDMI-A-1 on
niri msg output HDMI-A-1 mode 1920x1080@60.00
niri msg output HDMI-A-1 scale 1.4
