[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on   = "<C-f>"
run  = "filter"
desc = "filter"

[[mgr.prepend_keymap]]
on   = "C"
run  = ['yank', 'paste']
desc = "Duplicate and rename"

[[mgr.prepend_keymap]]
on   = "r"
run  = ['rename --empty=stem --cursor=start']
desc = "Better rename"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"
